### ISSUE TITLE
printf_buffered(), buffering for putchar_

### ISSUE THREAD

**Issue by kjsdf7wr3** [eyalroz/printf#104]
`printf `from `<stdio.h>` provides buffering via some other internal functions.
It would be nice, if this repo offered a `printf ` variant, which operates on a user provided buffer to reduce the calls to `putchar_`.

Example:
```c++
void puts_(const char * data, int length)
{
    // handle data block wise, instead of char wise like in putchar_
}

char buffer[10];
printf_buffered(buffer, sizeof(buffer), "0123456789+2");  // <-- calls puts_(buffer, 10); puts(buffer+10, 2);
printf_buffered(buffer, sizeof(buffer), "abc");          // <-- calls puts_(buffer, 3); 
```

Of course, one could also implement this kind of buffering inside `putchar_`, but at least if built without LTO, the performance would be quite a bit better for the `printf_buffered`.

**Comment by eyalroz** [comment]
This library's scope will not expand to also cover stream buffering. While it is certainly useful to have - if you want this...

* You can achieve this using `fctprintf()` - simply use a function which applies such buffering. 
* Write a library depending on libprintf, which utilizes either `fctprintf()`, or `sprintf_()` into its buffer,  to implement `printf_buffered()`.
