### ISSUE TITLE
Fails to compile without float support

### ISSUE THREAD

**Issue by sijk** [eyalroz/printf#118]
Compiling with `PRINTF_SUPPORT_DECIMAL_SPECIFIERS = 0` and `PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS = 0` fails because the following declarations are within the `#if (PRINTF_SUPPORT_DECIMAL_SPECIFIERS || PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS)` block but shouldn't be. 

```
printf_unsigned_value_t
printf_signed_value_t
numeric_base_t
printf_size_t
PRINTF_MAX_POSSIBLE_BUFFER_SIZE
```

I found this when working with v6.0.0 but I haven't traced back to see when the problem was introduced.

**Comment by eyalroz** [comment]
Thanks for reporting this. I should really try to get the GitHub Actions workflow to build with all possible combinations of the ON/OFF parameters.

Anyway, I rebased a bunch of commits and this is now fixed. Will soon post a new release candidate for v6.0.0
