### ISSUE TITLE
is there a API to printf vector?

### ISSUE THREAD

**Issue by esrrhs** [eyalroz/printf#147]
Hi, I was finding a library to printf a vector, the cpp code like this: 
```
Var v1(1), v2("aaa");
std::vector<Var> v = {v1, v2};
some_printf("%s %d", v);
```
I think the API can implement after modify some code in this repo, can you add this feature? or tell me where should I modify the code

thank you

**Comment by eyalroz** [comment]
Hello @esrrhs ,

Please note that this is a _C_ language library, not C++. It does not recognize any C++ features. To print vectors or other C++ ranges, you can using C++'s [`std::print()`](https://en.cppreference.com/w/cpp/io/print) function:
```
#include <vector>
#include <print>

int main() {
  auto v = std::vector<int>{1, 2, 3};
  std::print(std::cout, "{}", v);
}
```
or, if you compile your program with an older version of the  C++ standard, use the [fmt library](https://fmt.dev/latest/index.html) for the same effect:
```
#include <vector>
#include <fmt/ranges.h>

int main() {
  auto v = std::vector<int>{1, 2, 3};
  fmt::print("{}", v);
}
```
