### ISSUE TITLE
suspisious code vs comment

### ISSUE THREAD

**Issue by alexrayne** [eyalroz/printf#160]
Hallow, there is suspisious comment, that looks conflicts with a code
https://github.com/eyalroz/printf/blob/f8ed5a9bd9fa8384430973465e94aa14c925872d/src/printf/printf.c#L938C7-L938C7

```
  printf_size_t decimal_part_width =
    ((flags & FLAGS_LEFT) && exp10_part_width) ?
      // We're padding on the right, so the width constraint is the exponent part's
      // problem, not the decimal part's, so we'll use as many characters as we need:
      0U :
      // We're padding on the left; so the width constraint is the decimal part's
      // problem. Well, can both the decimal part and the exponent part fit within our overall width?
      ((width > exp10_part_width) ?
...
```
`((flags & FLAGS_LEFT) && exp10_part_width) ` obviously points about left-padding, but comment says about right one.

**Comment by eyalroz** [comment]
When we align left, we pad on the right. But thanks for taking the time to scrutinize the code! :-)
