### ISSUE TITLE
Suggest removing option to disable PRINTF_SUPPORT_PTRDIFF_LENGTH_MODIFIER

### ISSUE THREAD

**Issue by mickjc750** [eyalroz/printf#31]
When built for Cortex-M3 using GCC with -Os, this option has almost no affect on the build size.
From minimal options (all features disabled). Enabling this option actually reduced build size by 16 bytes, somehow.

**Comment by eyalroz** [comment]
Agreed... but I'll still need to look at mpaland's commit log and try to figure out why this was written in, in the first place.

**Comment by eyalroz** [comment]
Apparently no reason was given.
