### ISSUE TITLE
removal of out_fct_wrap_type

### ISSUE THREAD

**Issue by mickjc750** [eyalroz/printf#32]
This wrapper exists, as a means of passing a function pointer and a null pointer, from the interface function all the way down to the character output function, which itself is a function pointer based on the output mode. This is needed to provide fctprintf().

A better approach, is to instantiate a variable set (struct) particular to the output mode in the interface function. Then pass this by reference through to the character output function.
 This makes the character output function the same format (void (*out)(char, void*))  as that used by fctprintf().
This removes the need for a double function pointer de-reference per character which is a performance boost.
It also removes the need to pass the 'maxlen' parameter to most of the functions, where for most output modes it is unused.

**Comment by eyalroz** [comment]
I don't exactly follow what you're suggesting:

* `out_fct_wrap_type` is not exposed in the library interface.
* As for the double-dereferencing - we do currently have it, but I don't see how your suggestion would remove it: You seem to be suggesting we pass the function pointer through a pointer to a struct containing it.

Please clarify...

**Comment by mickjc750** [comment]
Not the function pointer. Only variables specific to the mode of output. It's difficult for me to explain, but I've already done this on an open PR, you can see the changes there.

**Comment by eyalroz** [comment]
Oh, now I see your PR.

But - it's a 44-commit PR; that doesn't make sense. I can't use it without spending hours, or days, on merging. To submit a PR, you start from the branch you're PR'ing against, and only apply one or a few changesets to get the effect you wanted.

Anyway, I don't mind using the struct you suggested, which basically a kind of a richer iterator than a raw pointer. I'll try to manually merge that change soon.

**Comment by eyalroz** [comment]
Hmm. This is interesting. This actually gives me the idea of doing something a little differentr:

* _Do_ wrap output functions.
* Use the wrapper for regular buffer output as well
* Have the wrapper take care of counting the number of characters printed
* Don't pass maxlen around at all... perhaps we can even avoid passing idx around entirely.
* Don't pass idx and maxlen to the output function - because they're supposed to have it.

**Comment by eyalroz** [comment]
Well, I was going to work on this, but then other issues came up. Now that there are no open bugs, I believe it might be a good idea to pause, make a release (v5.0 I suppose), then get back to this. What do you think, @mickjc750 ?

**Comment by mickjc750** [comment]
I agree, I have some other issues myself at the moment. It's working well enough for now.

**Comment by eyalroz** [comment]
@mickjc750 : So, this is happening... expect a PR soon. It will do away with 4 parameters + the return value in lots of functions :-)
