### ISSUE TITLE
sizeof(double) is not guaranteed to be 64bits 

### ISSUE THREAD

**Issue by mickjc750** [eyalroz/printf#37]
On AVR, and most likely some other 8-bit platforms, double is only 32bit. 
This breaks %e and %g (but not %f).
Ideally, it would be nice to provide some kind of %e %g functionality when double is 32bit, perhaps with reduced precision.
At a minimum, a build error should occur if %e and or %g is enabled on these platforms.

**Comment by eyalroz** [comment]
Hmm, you're right about the size. The standard apparently allows for smaller doubles.

How come it doesn't break `%f`, I wonder?

Anyway, I'll need to go over the code and see.
