### ISSUE TITLE
Build warning regarding sprint_exponential_number() when %ll and %f are enabled without %e

### ISSUE THREAD

**Issue by mickjc750** [eyalroz/printf#39]
The following build warning occurs with:
PRINTF_SUPPORT_FLOAT_SPECIFIERS   ON
PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS    OFF
PRINTF_SUPPORT_LONG_LONG     ON

Built with arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

app/src/printf.c: In function 'sprint_floating_point':
app/src/printf.c:779:10: warning: implicit declaration of function 'sprint_exponential_number'; did you mean 'sprint_decimal_number'? [-Wimplicit-function-declaration]
          sprint_exponential_number(out, buffer, idx, maxlen, value, precision, width, flags, buf, len) :
          ^~~~~~~~~~~~~~~~~~~~~~~~~
          sprint_decimal_number

**Comment by eyalroz** [comment]
How this?

**Comment by mickjc750** [comment]
@eyalroz yes that fixes it.

**Comment by eyalroz** [comment]
The issue will get auto-closed when the chage lands on the main branch...
