### ISSUE TITLE
Bad param in TEST_CASE for %20llX (test_suite)

### ISSUE THREAD

**Issue by csoroz** [eyalroz/printf#44]
This test case fails compiling with MSVC 2017 in Win32:
https://github.com/eyalroz/printf/blob/bd89cc74961ca2a723650ce430a9897f3de396ec/test/test_suite.cpp#L489
The call with `0U` is putting a 32 bit value on the stack but it needs 64 bits. Passing `0ULL` as parameter fixes it (I have checked with MSVC 2017).

https://en.cppreference.com/w/cpp/language/integer_literal

**Comment by eyalroz** [comment]
@csoroz : Thanks.

If you're using / planning to use this library an interesting project, please consider emailing me and letting me know. I want to beef up its credibility relative to mpaland's original repo: That one has all the stars while this one has many fixes, but you can't tell unless you look at the branch chart.
