### ISSUE TITLE
Pointer format %p fails (Win32)

### ISSUE THREAD

**Issue by csoroz** [eyalroz/printf#45]
The value is taken from `va_arg` initially here:
https://github.com/eyalroz/printf/blob/bd89cc74961ca2a723650ce430a9897f3de396ec/printf.c#L1058
When `sizeof(uintptr_t) != sizeof(long long)` (i.e. Win32) it tries to read `va_arg` again:
https://github.com/eyalroz/printf/blob/bd89cc74961ca2a723650ce430a9897f3de396ec/printf.c#L1071
which is wrong. The case when `is_ll` is true does it right:
https://github.com/eyalroz/printf/blob/bd89cc74961ca2a723650ce430a9897f3de396ec/printf.c#L1067
If the else case is corrected, it would do the same. Then this conditional compilation is not necessary:
`#if PRINTF_SUPPORT_LONG_LONG`

https://github.com/eyalroz/printf/blob/bd89cc74961ca2a723650ce430a9897f3de396ec/printf.c#L1055-L1078

Compiling with MSVC (VS2017) this issue makes this test cases fail:
<img width="646" alt="Screenshot 2021-09-21 at 17 49 03" src="https://user-images.githubusercontent.com/3624828/134203822-0f454a22-b9d4-465b-b224-e656f0cd73b5.png">

**Comment by eyalroz** [comment]
You are quite right. I seem to have messed this up when I streamlined the long long support.

What happens if you replace the `'p'` case section with the following? :
```
      case 'p' : {
        width = sizeof(void*) * 2U + 2; // 2 hex chars per byte + the "0x" prefix
        flags |= FLAGS_ZEROPAD | FLAGS_POINTER;
        uintptr_t value = (uintptr_t)va_arg(va, void*);
        idx = (value == (uintptr_t) NULL) ?
          _out_rev(out, buffer, idx, maxlen, ")lin(", 5, width, flags) :
          print_integer(out, buffer, idx, maxlen, (PRINTF_INTEGER_VALUE_TYPE) value, false, BASE_HEX, precision, width, flags);
        format++;
        break;
      }
```

**Comment by csoroz** [comment]
With that code it passes all test cases (Win32 & x64).
These are the results with:
 `#define TEST_WITH_NON_STANDARD_FORMAT_STRINGS` 

<img width="1241" alt="Screenshot 2021-09-22 at 00 32 13" src="https://user-images.githubusercontent.com/3624828/134256557-e628c880-6ddc-455a-bed8-292e496a88e2.png">

<img width="1239" alt="Screenshot 2021-09-22 at 00 27 14" src="https://user-images.githubusercontent.com/3624828/134256547-4da546ff-e482-4444-ab1d-4adc2f23811b.png">

**Comment by tomstorey** [comment]
Hi,

Im having some funny issues with %p. Ive grabbed the latest code that was committed yesterday.

I have a linker script that supplies two variables for the start and end of heap. When I objdump my binary I see:

```
00080100 g       .heap  00000000 _heap_start
000ff000 g       .heap  00000000 _heap_end
```

In my C file I am using the following code:

```c
extern size_t _heap_start;
extern size_t _heap_end;

void main(void) {
    const uint32_t *heap_start = (uint32_t*)&_heap_start;
    const uint32_t *heap_end = (uint32_t*)&_heap_end;

    printf(
        "heap_start %p, heap_end %p\r\n\r\n",
        heap_start, heap_end
    );
}
```

But the output I get in my terminal is

```
heap_start 0x000ff000, heap_end 0x000ff000
```

If I modify my printf statement to be the following:

```c
    printf(
        "heap_start 0x%08X, heap_end 0x%08X\r\n\r\n",
        (uint32_t)heap_start, (uint32_t)heap_end
    );
```

Then I see the expected output in my terminal.

```
heap_start 0x00080100, heap_end 0x000FF000
```

Curiously, if I have two printf statements like the following

```c
    printf(
        "heap_start %p, heap_end 0x%08X\r\n\r\n",
        heap_start, (uint32_t)heap_end
    );
    printf(
        "heap_start 0x%08X, heap_end %p\r\n\r\n",
        (uint32_t)heap_start, heap_end
    );
```

Then I see the following output in my terminal:

```
heap_start 0x000ff000, heap_end 0x00000000

heap_start 0x00080100, heap_end 0x00000000
```

Two different printf's, one for each pointer, simply results in 0x00000000 for both values.

Not sure if I just miss the point of %p or if something else is going on? Most other examples of printf I see online simply suggest passing the pointer variable name.

I am compiling for Motorola 68k, so Ive got long long's disabled, if that matters?

**Comment by tomstorey** [comment]
So, on the theory that %p is taking its argument from +1 position, I think I can confirm this:

```c
    printf(
        "heap_start 0x%08X, heap_end %p, %08X\r\n\r\n",
        (uint32_t)&_heap_start, (uint32_t*)_heap_end, 0x12345678
    );
```

gives

```
heap_start 0x00080100, heap_end 0x12345678, E8268C00
```

**Comment by eyalroz** [comment]
@tomstorey And you are seeing this with the development branch?

**Comment by tomstorey** [comment]
Oops, maybe not. I copied from master, but I now see that yesterdays update is in the develop branch.

I'll give this another try a bit later on and let you know how I go.

**Comment by eyalroz** [comment]
Also, please try to minimize the offending snippet to a single line, e.g. use numeric literals if possible; and as few specifiers as possible while still triggering a bug (now you have 3 - perhaps 2 are sufficient?)

**Comment by csoroz** [comment]
@tomstorey I think the behaviour you see there is consistent with the code prior to the fix (it is reading an extra `va_arg` parameter for "%p")

**Comment by tomstorey** [comment]
Yep, %p working fine with the latest copy from develop branch.

Although I had some issues with compilation which I fixed by moving lines 169-197 inside the ifdef ending line 160. There dont seem to be any references to those functions with all "floating point stuff" disabled. My understanding of all that and how to make it work is still a work in progress (Ive been putting together a homebrew toolchain for cross compilation, and getting floating point working has been a bit of a sticking point).

**Comment by eyalroz** [comment]
@tomstorey Pull again please, I've hidden more of the floating-point stuff within an `#if-#endif`.

**Comment by tomstorey** [comment]
Perfect, thanks (no errors). :-)

**Comment by eyalroz** [comment]
So, I'll mark this closed for now. Reopen if necessary.
