### ISSUE TITLE
I'd like %I64d to print int64_t, even it's not standard.

### ISSUE THREAD

**Issue by superzmy** [eyalroz/printf#51]
My company aways use fixed int type . It's very disgusting to use "%" PRI64d "".

**Comment by eyalroz** [comment]
I certainly agree that it's annoying and unintuitive to write `"%" PRI64d ""`.

Tell me, though... 

* Which compilers support this?
* Where is the exact specification of how this behaves?
* How widely used do you believe this is?

**Comment by superzmy** [comment]
use Preprocessor to select 
1. msvc mode only I32 I64
2. all 8,16,32,64.

**Comment by eyalroz** [comment]
@superzmy: Can you answer the rest of my questions though? 

@mickjc750 , what do you think?

**Comment by eyalroz** [comment]
@superzmy : ping.

@mickjc75 : also ping.

**Comment by mickjc750** [comment]
So far the GNU printf() has been the benchmark. I'd recommend keeping it that way.

**Comment by eyalroz** [comment]
@mickjc750 : Well, there's a positive and a negative aspect of it being a benchmark. Any valid format string for GNU printf is a valid format string for us (ignoring `%a` and long-long-double which we haven't implemented yet). But a malformed format GNU print format string being rejected by us as well has not been a principle of mine...

Let me put it to you this way: Suppose you could make this change in GNU printf as well. Would you have it support `%i8`, ... `%i64`?

**Comment by mickjc750** [comment]
@eyalroz yes I would. I agree that it's better than PRI64d.

**Comment by eyalroz** [comment]
@mickjc750 : So why not offer this as an optional feature? It can even default to OFF for GNU printf compatibility.

**Comment by mickjc750** [comment]
@eyalroz I see it as non-portable feature creep. Although I'm probably biased as I'm always in Debian.

**Comment by JakeSays** [comment]
I'm for this change. PRI64d is a mess.

**Comment by eyalroz** [comment]
@JakeSays : And what would you respond to mickjc750's claim that it's "non-portable feature creep"?

**Comment by JakeSays** [comment]
@eyalroz First, it's not "feature creep" if we as a community decide that it adds value. Secondly, if MSVC wasn't important then clang wouldn't have implemented compatibility for its syntax.

**Comment by eyalroz** [comment]
> if MSVC wasn't important then clang wouldn't have implemented compatibility for its syntax.

It does? Can I have a link to that?

**Comment by JakeSays** [comment]
https://clang.llvm.org/docs/MSVCCompatibility.html

**Comment by eyalroz** [comment]
@JakeSays : So, %I64 is supported with `-fms-extensions`?

Well, I think I'm sold. Let's add the `%I` format specifiers for 64, 32, 16 and 8. I will make them optional features though!

**Comment by eyalroz** [comment]
@JakeSays , @mickjc750 , @superzmy : Please have a look at PR #83 .

**Comment by eyalroz** [comment]
@superzmy : Please give the development branch a spin using %I specifiers...

**Comment by superzmy** [comment]
I don't understand what this means
【The I specifier is not in the C (nor C++) standard, but is somewhat popular, as it makes it easier to handle integer types of specific size. One must specify the argument size in bits immediately after the I: I8 for int8_t, I16 for int16_t, I32 for int32_t, I64 for int64_t. The printing is "integer-promotion-safe", i.e. the fact that an int8_t may actually be passed in promoted into a larger int will not prevent it from being printed using its origina value.
There is no unsigned equivalent of the I specifier at the moment.】
Usually we write "%I64d %I64u %I64x" in MSVC format. 'I' means signed or unsigned integer type, other than float type

**Comment by eyalroz** [comment]
@superzmy : Oh, sorry, I didn't update the documentation. Updated it now.

**Comment by phillipjohnston** [comment]
Can you please add #defines to compile-out this behavior for users who don't need it? It generates a ton of warnings for with Clang, and I don't want to disable `-Wformat` because it is useful for actual formatting problems.

**Comment by eyalroz** [comment]
@phillipjohnston Oh, I forgot the defines in the test suite... I'll fix that, of course.
