### ISSUE TITLE
ALIAS_STANDARD_FUNCTION_NAMES doesn't work correctly

### ISSUE THREAD

**Issue by KKoovalsky** [eyalroz/printf#67]
When setting the option `ALIAS_STANDARD_FUNCTION_NAMES` to `ON` only the definitions inside `printf.c` will be affected. Inside `printf.c` https://github.com/eyalroz/printf/blob/develop/src/printf/printf.c#L54:

```
#if PRINTF_ALIAS_STANDARD_FUNCTION_NAMES
# define printf_    printf
# define sprintf_   sprintf
# define vsprintf_  vsprintf
# define snprintf_  snprintf
# define vsnprintf_ vsnprintf
# define vprintf_   vprintf
#endif
```

But in the `printf.h` there is no include "printf_config.h", thus the declarations will never be aliased.

It means that, if the option is set to `ON` and the library is compiled, installed and consumed:

```
#include "printf.h"

int main()
{
    char c[64]; 
    snprintf(c, sizeof(c), "%d %f", 5, 160.1);

    return 0;
}
```

One gets compilation error:

> main.cpp: In function ‘int main()’:
main.cpp:6:12: error: ‘snprintf’ was not declared in this scope
    6 |     snprintf(c, sizeof(c), "%d %f", 5, 160.1);
       |     ^~~~~~~~

Possible solutions:
1. Install `printf_config.h` along with `printf.h` and put `#include "printf.h"` at the top of `printf.h`.
2. Generate `printf.h` and rename the function names basing on the `ALIAS_STANDARD_FUNCTION_NAMES` option value.
3. Generate `printf.h` by putting `PRINTF_ALIAS_STANDARD_FUNCTION_NAMES` macro dynamically at the top of the `printf.h` file during installation and use `target_compile_definitions(printf PUBLIC PRINTF_ALIAS_STANDARD_FUNCTION_NAMES)` for the build interface.
4. Other?

**Comment by eyalroz** [comment]
Let's first deal with your PR, then I'll get back to this.

**Comment by eyalroz** [comment]
> But in the `printf.h` there is no include "printf_config.h", 

Neither is there such an inclusion in `printf.c` ... unless you passed a compiler definition for that inclusion to happen.

> thus the declarations will never be aliased.

If you don't pass any compiler definitions to `printf.c`, nor to `printf.h`, then no aliasing will happen. 

To get aliasing, you need to write:
```
PRINTF_ALIAS_STANDARD_FUNCTION_NAMES
#include <printf/printf.h>

int main() {
    char c[64]; 
    snprintf(c, sizeof(c), "%d %f", 5, 160.1);
    return 0;
}
```
Why do you find this to be a problem?

**Comment by KKoovalsky** [comment]
> > But in the printf.h there is no include "printf_config.h",  

>Neither is there such an inclusion in printf.c ... unless you passed a compiler definition for that inclusion to happen.

This is not true. See: https://github.com/eyalroz/printf/blob/develop/CMakeLists.txt#L69. `PRINTF_INCLUDE_CONFIG_H` is always defined when compiling `printf.c`, so it means that this inclusion https://github.com/eyalroz/printf/blob/develop/src/printf/printf.c#L49 will take place.

The solution you have proposed will only work when the CMake option `PRINTF_ALIAS_STANDARD_FUNCTION_NAMES` is set to `ON`. Otherwise, one gets link error "symbol snprintf undefined", or `snprintf` from the standard library gets linked, what is wrong, obviously.

It's OK for me to have this duplication of `PRINTF_ALIAS_STANDARD_FUNCTION_NAMES`, but it should be documented properly.

**Comment by eyalroz** [comment]
> PRINTF_INCLUDE_CONFIG_H is always defined when compiling printf.c

... when you're building it with CMake. But the file itself doesn't automatically include it. But we're just splitting hairs here.

> The solution you have proposed will only work when the CMake option PRINTF_ALIAS_STANDARD_FUNCTION_NAMES is set to ON.

Well, yes, but you would use this only if you've built libprintf like that. That's intentional.

... however, I suppose I can sympathize with the desire for users not having to specify preprocessor defines to match the build options. Still, I really would not like to generate `printf.h`

> It's OK for me to have this duplication of PRINTF_ALIAS_STANDARD_FUNCTION_NAMES, but it should be documented properly.

I'll add some relevant text to the README.
