### ISSUE TITLE
Test suite won't build with standard function aliasing on, due to catch

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/printf#85]
The catch unit-testing framework includes  the C standard library's printf-family functions; consequently, it clashes with our library when we alias the standard printf-family function names. In the past this was circumvented by including `printf.c` within a namespace, but now that `printf.c` is more language-aware, that's not possible; plus, it wasn't a good idea, since it was testing something others than what library users will actually be doing.

Anyway, now we have this clash. This means either we need to not run the test suite with the aliased names, or ... do something else?

**Comment by phillipjohnston** [comment]
Huh... I'm not using your build system (libc is using Meson), but I do have aliasing enabled and the tests build for me.

**Comment by phillipjohnston** [comment]
I was wrong, looks like that compiler arg isn't applied to the test suite! Sorry for the distraction.
