### ISSUE TITLE
I have a problem there

### ISSUE THREAD

**Issue by bingheng-wlm** [eyalroz/printf#86]
```
printf.c:(.text+0x790): undefined reference to `__stack_chk_fail'
ld: printf.o: in function `print_decimal_number':
printf.c:(.text+0x12e6): undefined reference to `__stack_chk_fail'
ld: printf.o: in function `print_exponential_number':
printf.c:(.text+0x1a33): undefined reference to `__stack_chk_fail'
ld: printf.o: in function `print_floating_point':
printf.c:(.text+0x1d65): undefined reference to `__stack_chk_fail'
ld: printf.o:printf.c:(.text+0x33ce): more undefined references to `__stack_chk_fail' follow
```
just this.
So, ......
why?

**Comment by eyalroz** [comment]
This is likely a problem with your compiler or linker.

How are you building the library? How are you linking your executable?

**Comment by phillipjohnston** [comment]
If your standard library does not have a stack protector implementation, this will happen.

You can turn this off with -fno-stack-protector compiler argument, or you can supply an implementation for the stack protection functions: https://embeddedartistry.com/blog/2020/05/18/implementing-stack-smashing-protection-for-microcontrollers-and-embedded-artistrys-libc/

**Comment by eyalroz** [comment]
@phillipjohnston : Can you explain what's going on? Is my library doing something problematic? Regardless, given what you've said, perhaps the `CMakeLists.txt` should detect this "lack of stack protector", when one is needed.

**Comment by phillipjohnston** [comment]
@eyalroz if the software is built with -fstack-protector or similar flags (which may or may not be done by default), when certain conditions are detected the compiler will insert code to check whether or not a function is smashing the stack. Some implementations of the standard library don't come with this function (such as arm-gcc), so it will cause a linker error if it is not implemented but the compiler emitted those functions. My notes were meant for @bingheng-wen.

I don't really think it's a responsibility of your library to handle this, but if more people report it you could add a convenience option to disable stack smashing protection. (-fno-stack-protector for gcc/clang)

**Comment by eyalroz** [comment]
Do you mean having that as a PRIVATE compilation flag for the `.a`/`.so` file, or as an INTERFACE compilation flag for code  using the library?

**Comment by phillipjohnston** [comment]
Again, I think that it is proper for it to be handled outside of your library, but if you were to add it to your library it would be better to add it as a PRIVATE compilation flag.

**Comment by eyalroz** [comment]
Agreeing with @phillipjohnston : It's not this library's fault or responsibility.
