### ISSUE TITLE
Silent narrowing conversion(s) from size_t to printf_size_t may bite us

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/printf#87]
printf()-family functions have the questionable design choice of returning `int` as the number of characters printed, despite buffer lengths possibly being larger than `INT_MAX`. 

In our implementation, this is compounded by us using an int-sized `printf_size_t` type for offsets and lengths within the buffer, corresponding to the final return type - while taking in a `size_t` for functions such as `snprintf()`. At the moment, we simply cast from the latter into the former type at various locations, never checking for overflow. This could theoretically result in us getting lengths of 0, or other short lengths, which will mess up our behavior.

We need to cast as early as possible, and discard the `size_t`  inputs.

**Comment by phillipjohnston** [comment]
There are still some implicit casts on the development branch - I will create a PR for those.

**Comment by eyalroz** [comment]
So, your PR #97 had one such cast - have you noticed others?

Also, in my defense, that cast was not that implicit - it was in an assignment; and it's where I want the cast to happen. But the PR is merged.

**Comment by phillipjohnston** [comment]
That was the only one, and I just used the warning term, not asking you to defend yourself :)
