### ISSUE TITLE
Missing tests for floating point with integral > 2^31 -1

### ISSUE THREAD

**Issue by jrahlf** [eyalroz/printf#93]
While working on #84, I noticed that the test coverage for large floating point values seems insufficient.
When changing the integral field type to `int32_t`, the test suite still passes. This makes me believe that there is no test case for floating point values with the integral part > `2^31 -1`.
https://github.com/eyalroz/printf/blob/36ad0167c1378907c07611b6b3d13ab3b07a78da/src/printf/printf.c#L423

**Comment by eyalroz** [comment]
I'll have a look.

**Comment by eyalroz** [comment]
@jrahlf : How's this?

**Comment by jrahlf** [comment]
Now fails for 32-bit integral type as it should.

**Comment by eyalroz** [comment]
@jrahlf : Hmm... should it, though? Or - do you mean, on the version you're working on, which uses 32-bit-integers only, internally?

**Comment by jrahlf** [comment]
What I meant: if you change the type from `uint_fast64_t` to `uint32_t`, the test suite fails.

**Comment by eyalroz** [comment]
I think we're ok now.
